export const users = [
{   id:1, 
    firstName:'jane', 
    lastName:'joe', 
    email:'jane@gmail.com',
    password:'jane5555', 
    address:'wakiso', 
    bio: 'born in November 4, 1989',
    occupation: 'unversity student',
    expertise: 'student of law', 
    admin: false,
    mentor:false
},
{   id:2, 
    firstName:'sherifa', 
    lastName:'mogan', 
    email:'sherifa@gmail.com',
    password:'sherifa5555', 
    address:'kigali', 
    bio: 'Born in december 6, 1990',
    occupation: 'software developer',
    expertise: 'honors a bachalors degree in computer science',
    admin: true,
    mentor:false
},
{   id:3, 
    firstName:'betty', 
    lastName:'grace', 
    email:'betty@gmail.com',
    password:'betty5555', 
    address:'hoima', 
    bio: 'Born in may 20, 1995',
    occupation: 'entreprenuer',
    expertise: 'honors a bachalors degree in business adminstration',
    admin: false,
    mentor:false

},
{   id:4, 
    firstName:'martin', 
    lastName:'luther', 
    email:'martin@gmail.com',
    password:'martin5555', 
    address:'kigali', 
    bio: 'Born on November 4, 1956',
    occupation: ' professional lawyer',
    expertise: 'law activist and politician',
    admin: false,
    mentor:true
},
{   id:5, 
    firstName:'john', 
    lastName:'blaq', 
    email:'john@gmail.com',
    password:'john5555', 
    address:'kampala', 
    bio: 'Born on may 4, 1982',
    occupation: 'leader of human rights movement',
    expertise: 'activist, politician and a successful entreprenuer', 
    admin: false,
    mentor:true
},
{   id:6, 
    firstName:'billy', 
    lastName:'blanks', 
    email:'billy@gmail.com',
    password:'billy5555', 
    address:'lagos', 
    bio: 'Born on November 4, 1956',
    occupation: 'fashion designer',
    expertise: 'stage modeling, fashion and design',
    admin: false,
    mentor:true
}

    ];